### ISSUE TITLE
Let the script guess the imdb id for the movie?

### ISSUE THREAD

**Issue by gadelkareem** [fracpete/kodi-nfo-generator#3]
Anyway to let the script guess the IMDB for the movie?

**Comment by fracpete** [comment]
That functionality is already available through [scrapers](https://kodi.wiki/view/Scrapers).

**Comment by gadelkareem** [comment]
But those don't add the imdb file right?

**Comment by fracpete** [comment]
No, they generate the .nfo files directly.

**Comment by gadelkareem** [comment]
I looked kodi scrappers and the only one I found was TinyMediaManager which is a GUI app. Can you name one or two of those?

**Comment by fracpete** [comment]
I don't use any scrapers, as my directory naming generated rather poor results.

From a quick Google, you might want to have a look at this one:

https://kodi.tv/addons/matrix/metadata.universal

**Comment by fracpete** [comment]
Commit e5237c2c2fb3919f6d10417693a1f0a178edc2bd adds a simple tool called `kodi-nfo-guess` that searches IMDB for title matches and then outputs the `.imdb` file.
