### ISSUE TITLE
http 403 

### ISSUE THREAD

**Issue by beaverdude** [fracpete/kodi-nfo-generator#5]
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.imdb.com:443
DEBUG:urllib3.connectionpool:https://www.imdb.com:443 "GET /title/ttxxx/ HTTP/1.1" 403 118
CRITICAL:root:Failed to retrieve URL (status code 403): https://www.imdb.com/title/ttxxx/

it looks like imdb started filtering scraping.

**Comment by fracpete** [comment]
I just merged the following PR: https://github.com/fracpete/kodi-nfo-generator/pull/6

Maybe setting a user agent solves the problem for you?

**Comment by fracpete** [comment]
Also, commit f7187f9551f974eeb389f7bd3b4904b7db2093ba now only makes a request to IMDB when either the `--overwite` flag is provided or the `.nfo` is not yet present. Subsequent runs would only make requests for not yet processed movies. Commit 43495e71d174e006ae7305d1257e7b74948479bb also omits the delay when not writing a file (regression from earlier versions).

**Comment by fracpete** [comment]
It's still working for me (with only a few requests to IMDB), so I'm closing it for the time being.
